import { Suspense } from "react";
import { Route, Routes } from "react-router-dom";
import MainLayout from "./layouts/MainLayout";
import { publicRoutes } from "./routes";
import { spotifyAPIDelete } from "./utils/httpRequest";

function App() {
  const playlists = {
    href: "https://api.spotify.com/v1/users/31gcx7qzn7bcsyh6vn72rul4afki/playlists?offset=0&limit=50&locale=en-US,en;q%3D0.9,vi;q%3D0.8",
    limit: 50,
    next: null,
    offset: 0,
    previous: null,
    total: 41,
    items: [
      {
        collaborative: false,
        description: "",
        external_urls: {
          spotify: "https://open.spotify.com/playlist/5ycYBC6ksMGSpFnBJy0Wft",
        },
        href: "https://api.spotify.com/v1/playlists/5ycYBC6ksMGSpFnBJy0Wft",
        id: "5ycYBC6ksMGSpFnBJy0Wft",
        images: null,
        name: "a",
        owner: {
          display_name: "Khánh Lê Mai Quốc",
          external_urls: {
            spotify: "https://open.spotify.com/user/31gcx7qzn7bcsyh6vn72rul4afki",
          },
          href: "https://api.spotify.com/v1/users/31gcx7qzn7bcsyh6vn72rul4afki",
          id: "31gcx7qzn7bcsyh6vn72rul4afki",
          type: "user",
          uri: "spotify:user:31gcx7qzn7bcsyh6vn72rul4afki",
        },
        primary_color: null,
        public: true,
        snapshot_id: "AAAAAdnVlu56X6gyA54HZqzpBwbJfacF",
        tracks: {
          href: "https://api.spotify.com/v1/playlists/5ycYBC6ksMGSpFnBJy0Wft/tracks",
          total: 0,
        },
        type: "playlist",
        uri: "spotify:playlist:5ycYBC6ksMGSpFnBJy0Wft",
      },
      {
        collaborative: false,
        description: "",
        external_urls: {
          spotify: "https://open.spotify.com/playlist/6Zrj4wjfZZ7Z3LjAxgL9NK",
        },
        href: "https://api.spotify.com/v1/playlists/6Zrj4wjfZZ7Z3LjAxgL9NK",
        id: "6Zrj4wjfZZ7Z3LjAxgL9NK",
        images: null,
        name: "1234",
        owner: {
          display_name: "Khánh Lê Mai Quốc",
          external_urls: {
            spotify: "https://open.spotify.com/user/31gcx7qzn7bcsyh6vn72rul4afki",
          },
          href: "https://api.spotify.com/v1/users/31gcx7qzn7bcsyh6vn72rul4afki",
          id: "31gcx7qzn7bcsyh6vn72rul4afki",
          type: "user",
          uri: "spotify:user:31gcx7qzn7bcsyh6vn72rul4afki",
        },
        primary_color: null,
        public: true,
        snapshot_id: "AAAAAR4yXZ3huvTRmGGnoILkBaarETDt",
        tracks: {
          href: "https://api.spotify.com/v1/playlists/6Zrj4wjfZZ7Z3LjAxgL9NK/tracks",
          total: 0,
        },
        type: "playlist",
        uri: "spotify:playlist:6Zrj4wjfZZ7Z3LjAxgL9NK",
      },
      {
        collaborative: false,
        description: "",
        external_urls: {
          spotify: "https://open.spotify.com/playlist/5mWv4Dj9CP8UlXLDLuPGtX",
        },
        href: "https://api.spotify.com/v1/playlists/5mWv4Dj9CP8UlXLDLuPGtX",
        id: "5mWv4Dj9CP8UlXLDLuPGtX",
        images: null,
        name: "123",
        owner: {
          display_name: "Khánh Lê Mai Quốc",
          external_urls: {
            spotify: "https://open.spotify.com/user/31gcx7qzn7bcsyh6vn72rul4afki",
          },
          href: "https://api.spotify.com/v1/users/31gcx7qzn7bcsyh6vn72rul4afki",
          id: "31gcx7qzn7bcsyh6vn72rul4afki",
          type: "user",
          uri: "spotify:user:31gcx7qzn7bcsyh6vn72rul4afki",
        },
        primary_color: null,
        public: true,
        snapshot_id: "AAAAARUmFGBTCg/nflNMaL/hvzruyErl",
        tracks: {
          href: "https://api.spotify.com/v1/playlists/5mWv4Dj9CP8UlXLDLuPGtX/tracks",
          total: 0,
        },
        type: "playlist",
        uri: "spotify:playlist:5mWv4Dj9CP8UlXLDLuPGtX",
      },
      {
        collaborative: false,
        description: "123",
        external_urls: {
          spotify: "https://open.spotify.com/playlist/7HU7lQ011ADMZ2lPpShmgK",
        },
        href: "https://api.spotify.com/v1/playlists/7HU7lQ011ADMZ2lPpShmgK",
        id: "7HU7lQ011ADMZ2lPpShmgK",
        images: [
          {
            height: null,
            url: "https://i.scdn.co/image/ab67616d00001e02c006b0181a3846c1c63e178f",
            width: null,
          },
        ],
        name: "Tui la ai",
        owner: {
          display_name: "Khánh Lê Mai Quốc",
          external_urls: {
            spotify: "https://open.spotify.com/user/31gcx7qzn7bcsyh6vn72rul4afki",
          },
          href: "https://api.spotify.com/v1/users/31gcx7qzn7bcsyh6vn72rul4afki",
          id: "31gcx7qzn7bcsyh6vn72rul4afki",
          type: "user",
          uri: "spotify:user:31gcx7qzn7bcsyh6vn72rul4afki",
        },
        primary_color: null,
        public: true,
        snapshot_id: "AAAAA21XbqNifCQ5t+E1SZhtR6p2XD4k",
        tracks: {
          href: "https://api.spotify.com/v1/playlists/7HU7lQ011ADMZ2lPpShmgK/tracks",
          total: 2,
        },
        type: "playlist",
        uri: "spotify:playlist:7HU7lQ011ADMZ2lPpShmgK",
      },
      {
        collaborative: false,
        description: "123",
        external_urls: {
          spotify: "https://open.spotify.com/playlist/7G0wZlNNnn6z3RkcsXbn9J",
        },
        href: "https://api.spotify.com/v1/playlists/7G0wZlNNnn6z3RkcsXbn9J",
        id: "7G0wZlNNnn6z3RkcsXbn9J",
        images: [
          {
            height: null,
            url: "https://i.scdn.co/image/ab67616d00001e02c006b0181a3846c1c63e178f",
            width: null,
          },
        ],
        name: "Tôi là ai?",
        owner: {
          display_name: "Khánh Lê Mai Quốc",
          external_urls: {
            spotify: "https://open.spotify.com/user/31gcx7qzn7bcsyh6vn72rul4afki",
          },
          href: "https://api.spotify.com/v1/users/31gcx7qzn7bcsyh6vn72rul4afki",
          id: "31gcx7qzn7bcsyh6vn72rul4afki",
          type: "user",
          uri: "spotify:user:31gcx7qzn7bcsyh6vn72rul4afki",
        },
        primary_color: null,
        public: true,
        snapshot_id: "AAAABDkOstD4r6HDva2dVgOgJ1TckuuA",
        tracks: {
          href: "https://api.spotify.com/v1/playlists/7G0wZlNNnn6z3RkcsXbn9J/tracks",
          total: 3,
        },
        type: "playlist",
        uri: "spotify:playlist:7G0wZlNNnn6z3RkcsXbn9J",
      },
      {
        collaborative: false,
        description: "Obito, RAP VIỆT, Đen and more",
        external_urls: {
          spotify: "https://open.spotify.com/playlist/37i9dQZF1E38ztaiPmjAnf",
        },
        href: "https://api.spotify.com/v1/playlists/37i9dQZF1E38ztaiPmjAnf",
        id: "37i9dQZF1E38ztaiPmjAnf",
        images: [
          {
            height: null,
            url: "https://dailymix-images.scdn.co/v2/img/ab6761610000e5eba385bd3e0f67945f277792c2/1/en/default",
            width: null,
          },
        ],
        name: "Daily Mix 1",
        owner: {
          display_name: "Spotify",
          external_urls: {
            spotify: "https://open.spotify.com/user/spotify",
          },
          href: "https://api.spotify.com/v1/users/spotify",
          id: "spotify",
          type: "user",
          uri: "spotify:user:spotify",
        },
        primary_color: null,
        public: true,
        snapshot_id: "AAAAAAAAAAC5YGw8au7HluKtb/ehF7YJ",
        tracks: {
          href: "https://api.spotify.com/v1/playlists/37i9dQZF1E38ztaiPmjAnf/tracks",
          total: 50,
        },
        type: "playlist",
        uri: "spotify:playlist:37i9dQZF1E38ztaiPmjAnf",
      },
      {
        collaborative: false,
        description: "13",
        external_urls: {
          spotify: "https://open.spotify.com/playlist/2GujF8AlKTZ3CZlwPXUMKe",
        },
        href: "https://api.spotify.com/v1/playlists/2GujF8AlKTZ3CZlwPXUMKe",
        id: "2GujF8AlKTZ3CZlwPXUMKe",
        images: null,
        name: "khanhdua2",
        owner: {
          display_name: "Khánh Lê Mai Quốc",
          external_urls: {
            spotify: "https://open.spotify.com/user/31gcx7qzn7bcsyh6vn72rul4afki",
          },
          href: "https://api.spotify.com/v1/users/31gcx7qzn7bcsyh6vn72rul4afki",
          id: "31gcx7qzn7bcsyh6vn72rul4afki",
          type: "user",
          uri: "spotify:user:31gcx7qzn7bcsyh6vn72rul4afki",
        },
        primary_color: null,
        public: true,
        snapshot_id: "AAAAAfYhoqdallNnEhPlBXQlIX8wSf+E",
        tracks: {
          href: "https://api.spotify.com/v1/playlists/2GujF8AlKTZ3CZlwPXUMKe/tracks",
          total: 0,
        },
        type: "playlist",
        uri: "spotify:playlist:2GujF8AlKTZ3CZlwPXUMKe",
      },
      {
        collaborative: false,
        description: "",
        external_urls: {
          spotify: "https://open.spotify.com/playlist/545JCTx1ZlQ7XLT1p58u9n",
        },
        href: "https://api.spotify.com/v1/playlists/545JCTx1ZlQ7XLT1p58u9n",
        id: "545JCTx1ZlQ7XLT1p58u9n",
        images: null,
        name: "abc123",
        owner: {
          display_name: "Khánh Lê Mai Quốc",
          external_urls: {
            spotify: "https://open.spotify.com/user/31gcx7qzn7bcsyh6vn72rul4afki",
          },
          href: "https://api.spotify.com/v1/users/31gcx7qzn7bcsyh6vn72rul4afki",
          id: "31gcx7qzn7bcsyh6vn72rul4afki",
          type: "user",
          uri: "spotify:user:31gcx7qzn7bcsyh6vn72rul4afki",
        },
        primary_color: null,
        public: true,
        snapshot_id: "AAAAAlWGqcrz6Y7nfP+FQzcmms7ZYdgr",
        tracks: {
          href: "https://api.spotify.com/v1/playlists/545JCTx1ZlQ7XLT1p58u9n/tracks",
          total: 0,
        },
        type: "playlist",
        uri: "spotify:playlist:545JCTx1ZlQ7XLT1p58u9n",
      },
      {
        collaborative: false,
        description: "",
        external_urls: {
          spotify: "https://open.spotify.com/playlist/2eCK1heixRBW4BJScloqDF",
        },
        href: "https://api.spotify.com/v1/playlists/2eCK1heixRBW4BJScloqDF",
        id: "2eCK1heixRBW4BJScloqDF",
        images: null,
        name: "123",
        owner: {
          display_name: "Khánh Lê Mai Quốc",
          external_urls: {
            spotify: "https://open.spotify.com/user/31gcx7qzn7bcsyh6vn72rul4afki",
          },
          href: "https://api.spotify.com/v1/users/31gcx7qzn7bcsyh6vn72rul4afki",
          id: "31gcx7qzn7bcsyh6vn72rul4afki",
          type: "user",
          uri: "spotify:user:31gcx7qzn7bcsyh6vn72rul4afki",
        },
        primary_color: null,
        public: true,
        snapshot_id: "AAAAAWykeL73sm84J5RnEjtKpzRRGMDd",
        tracks: {
          href: "https://api.spotify.com/v1/playlists/2eCK1heixRBW4BJScloqDF/tracks",
          total: 0,
        },
        type: "playlist",
        uri: "spotify:playlist:2eCK1heixRBW4BJScloqDF",
      },
      {
        collaborative: false,
        description: "",
        external_urls: {
          spotify: "https://open.spotify.com/playlist/5MgHkmDyc7YAFh1lYBpxd6",
        },
        href: "https://api.spotify.com/v1/playlists/5MgHkmDyc7YAFh1lYBpxd6",
        id: "5MgHkmDyc7YAFh1lYBpxd6",
        images: null,
        name: "123",
        owner: {
          display_name: "Khánh Lê Mai Quốc",
          external_urls: {
            spotify: "https://open.spotify.com/user/31gcx7qzn7bcsyh6vn72rul4afki",
          },
          href: "https://api.spotify.com/v1/users/31gcx7qzn7bcsyh6vn72rul4afki",
          id: "31gcx7qzn7bcsyh6vn72rul4afki",
          type: "user",
          uri: "spotify:user:31gcx7qzn7bcsyh6vn72rul4afki",
        },
        primary_color: null,
        public: true,
        snapshot_id: "AAAAAQHZCa0b2svN9MTDHhiweHwJUq1F",
        tracks: {
          href: "https://api.spotify.com/v1/playlists/5MgHkmDyc7YAFh1lYBpxd6/tracks",
          total: 0,
        },
        type: "playlist",
        uri: "spotify:playlist:5MgHkmDyc7YAFh1lYBpxd6",
      },
      {
        collaborative: false,
        description: "",
        external_urls: {
          spotify: "https://open.spotify.com/playlist/6MkFHLDBfOMKg2l3zL3sLd",
        },
        href: "https://api.spotify.com/v1/playlists/6MkFHLDBfOMKg2l3zL3sLd",
        id: "6MkFHLDBfOMKg2l3zL3sLd",
        images: null,
        name: "123",
        owner: {
          display_name: "Khánh Lê Mai Quốc",
          external_urls: {
            spotify: "https://open.spotify.com/user/31gcx7qzn7bcsyh6vn72rul4afki",
          },
          href: "https://api.spotify.com/v1/users/31gcx7qzn7bcsyh6vn72rul4afki",
          id: "31gcx7qzn7bcsyh6vn72rul4afki",
          type: "user",
          uri: "spotify:user:31gcx7qzn7bcsyh6vn72rul4afki",
        },
        primary_color: null,
        public: true,
        snapshot_id: "AAAAAWz74rsVfJl1H5Nxrj3KJJ+8uNm6",
        tracks: {
          href: "https://api.spotify.com/v1/playlists/6MkFHLDBfOMKg2l3zL3sLd/tracks",
          total: 0,
        },
        type: "playlist",
        uri: "spotify:playlist:6MkFHLDBfOMKg2l3zL3sLd",
      },
      {
        collaborative: false,
        description: "",
        external_urls: {
          spotify: "https://open.spotify.com/playlist/0ibOdHCaJsB60H9VSOVW6i",
        },
        href: "https://api.spotify.com/v1/playlists/0ibOdHCaJsB60H9VSOVW6i",
        id: "0ibOdHCaJsB60H9VSOVW6i",
        images: null,
        name: "123",
        owner: {
          display_name: "Khánh Lê Mai Quốc",
          external_urls: {
            spotify: "https://open.spotify.com/user/31gcx7qzn7bcsyh6vn72rul4afki",
          },
          href: "https://api.spotify.com/v1/users/31gcx7qzn7bcsyh6vn72rul4afki",
          id: "31gcx7qzn7bcsyh6vn72rul4afki",
          type: "user",
          uri: "spotify:user:31gcx7qzn7bcsyh6vn72rul4afki",
        },
        primary_color: null,
        public: true,
        snapshot_id: "AAAAAWwGQb3SE5BwA1IG/6/VIlQpjheh",
        tracks: {
          href: "https://api.spotify.com/v1/playlists/0ibOdHCaJsB60H9VSOVW6i/tracks",
          total: 0,
        },
        type: "playlist",
        uri: "spotify:playlist:0ibOdHCaJsB60H9VSOVW6i",
      },
      {
        collaborative: false,
        description: "",
        external_urls: {
          spotify: "https://open.spotify.com/playlist/66d0BbjHLfeNYoqOvEGBWZ",
        },
        href: "https://api.spotify.com/v1/playlists/66d0BbjHLfeNYoqOvEGBWZ",
        id: "66d0BbjHLfeNYoqOvEGBWZ",
        images: null,
        name: "123",
        owner: {
          display_name: "Khánh Lê Mai Quốc",
          external_urls: {
            spotify: "https://open.spotify.com/user/31gcx7qzn7bcsyh6vn72rul4afki",
          },
          href: "https://api.spotify.com/v1/users/31gcx7qzn7bcsyh6vn72rul4afki",
          id: "31gcx7qzn7bcsyh6vn72rul4afki",
          type: "user",
          uri: "spotify:user:31gcx7qzn7bcsyh6vn72rul4afki",
        },
        primary_color: null,
        public: true,
        snapshot_id: "AAAAAV1ViShF7ESyIjwPoCZ+Yxjhrp/l",
        tracks: {
          href: "https://api.spotify.com/v1/playlists/66d0BbjHLfeNYoqOvEGBWZ/tracks",
          total: 0,
        },
        type: "playlist",
        uri: "spotify:playlist:66d0BbjHLfeNYoqOvEGBWZ",
      },
      {
        collaborative: false,
        description: "",
        external_urls: {
          spotify: "https://open.spotify.com/playlist/4hUFrNCwMiNySnMWeli0sK",
        },
        href: "https://api.spotify.com/v1/playlists/4hUFrNCwMiNySnMWeli0sK",
        id: "4hUFrNCwMiNySnMWeli0sK",
        images: null,
        name: "123",
        owner: {
          display_name: "Khánh Lê Mai Quốc",
          external_urls: {
            spotify: "https://open.spotify.com/user/31gcx7qzn7bcsyh6vn72rul4afki",
          },
          href: "https://api.spotify.com/v1/users/31gcx7qzn7bcsyh6vn72rul4afki",
          id: "31gcx7qzn7bcsyh6vn72rul4afki",
          type: "user",
          uri: "spotify:user:31gcx7qzn7bcsyh6vn72rul4afki",
        },
        primary_color: null,
        public: true,
        snapshot_id: "AAAAAfdG3819KrM9oPlvt71uiOTqenSB",
        tracks: {
          href: "https://api.spotify.com/v1/playlists/4hUFrNCwMiNySnMWeli0sK/tracks",
          total: 0,
        },
        type: "playlist",
        uri: "spotify:playlist:4hUFrNCwMiNySnMWeli0sK",
      },
      {
        collaborative: false,
        description: "12312313123",
        external_urls: {
          spotify: "https://open.spotify.com/playlist/1N7Tx7xbff8oolpYzEESuc",
        },
        href: "https://api.spotify.com/v1/playlists/1N7Tx7xbff8oolpYzEESuc",
        id: "1N7Tx7xbff8oolpYzEESuc",
        images: null,
        name: "Tui la ai42234234",
        owner: {
          display_name: "Khánh Lê Mai Quốc",
          external_urls: {
            spotify: "https://open.spotify.com/user/31gcx7qzn7bcsyh6vn72rul4afki",
          },
          href: "https://api.spotify.com/v1/users/31gcx7qzn7bcsyh6vn72rul4afki",
          id: "31gcx7qzn7bcsyh6vn72rul4afki",
          type: "user",
          uri: "spotify:user:31gcx7qzn7bcsyh6vn72rul4afki",
        },
        primary_color: null,
        public: true,
        snapshot_id: "AAAAAZp6VScIpYH/K0cQ7iIGaLjk4tVj",
        tracks: {
          href: "https://api.spotify.com/v1/playlists/1N7Tx7xbff8oolpYzEESuc/tracks",
          total: 0,
        },
        type: "playlist",
        uri: "spotify:playlist:1N7Tx7xbff8oolpYzEESuc",
      },
      {
        collaborative: false,
        description: "12312313123",
        external_urls: {
          spotify: "https://open.spotify.com/playlist/3HUi1LQkoDsnJgazpQmr58",
        },
        href: "https://api.spotify.com/v1/playlists/3HUi1LQkoDsnJgazpQmr58",
        id: "3HUi1LQkoDsnJgazpQmr58",
        images: null,
        name: "Tui la ai",
        owner: {
          display_name: "Khánh Lê Mai Quốc",
          external_urls: {
            spotify: "https://open.spotify.com/user/31gcx7qzn7bcsyh6vn72rul4afki",
          },
          href: "https://api.spotify.com/v1/users/31gcx7qzn7bcsyh6vn72rul4afki",
          id: "31gcx7qzn7bcsyh6vn72rul4afki",
          type: "user",
          uri: "spotify:user:31gcx7qzn7bcsyh6vn72rul4afki",
        },
        primary_color: null,
        public: true,
        snapshot_id: "AAAAATCdwRAdni+uMpXOi6p47K46RWVW",
        tracks: {
          href: "https://api.spotify.com/v1/playlists/3HUi1LQkoDsnJgazpQmr58/tracks",
          total: 0,
        },
        type: "playlist",
        uri: "spotify:playlist:3HUi1LQkoDsnJgazpQmr58",
      },
      {
        collaborative: false,
        description: "",
        external_urls: {
          spotify: "https://open.spotify.com/playlist/09wtPrcPNl1mV5li5zKsSS",
        },
        href: "https://api.spotify.com/v1/playlists/09wtPrcPNl1mV5li5zKsSS",
        id: "09wtPrcPNl1mV5li5zKsSS",
        images: null,
        name: "Khanhdua2@",
        owner: {
          display_name: "Khánh Lê Mai Quốc",
          external_urls: {
            spotify: "https://open.spotify.com/user/31gcx7qzn7bcsyh6vn72rul4afki",
          },
          href: "https://api.spotify.com/v1/users/31gcx7qzn7bcsyh6vn72rul4afki",
          id: "31gcx7qzn7bcsyh6vn72rul4afki",
          type: "user",
          uri: "spotify:user:31gcx7qzn7bcsyh6vn72rul4afki",
        },
        primary_color: null,
        public: true,
        snapshot_id: "AAAAAQ8dIH4n/MZLk/il+E8ZEaXQXLkS",
        tracks: {
          href: "https://api.spotify.com/v1/playlists/09wtPrcPNl1mV5li5zKsSS/tracks",
          total: 0,
        },
        type: "playlist",
        uri: "spotify:playlist:09wtPrcPNl1mV5li5zKsSS",
      },
      {
        collaborative: false,
        description: "",
        external_urls: {
          spotify: "https://open.spotify.com/playlist/2JJKPRr2ODC4sYEVop2jTm",
        },
        href: "https://api.spotify.com/v1/playlists/2JJKPRr2ODC4sYEVop2jTm",
        id: "2JJKPRr2ODC4sYEVop2jTm",
        images: null,
        name: "Tui la ai v",
        owner: {
          display_name: "Khánh Lê Mai Quốc",
          external_urls: {
            spotify: "https://open.spotify.com/user/31gcx7qzn7bcsyh6vn72rul4afki",
          },
          href: "https://api.spotify.com/v1/users/31gcx7qzn7bcsyh6vn72rul4afki",
          id: "31gcx7qzn7bcsyh6vn72rul4afki",
          type: "user",
          uri: "spotify:user:31gcx7qzn7bcsyh6vn72rul4afki",
        },
        primary_color: null,
        public: true,
        snapshot_id: "AAAAAZFoZIknUSoywP61Lgj+OvHmpJUv",
        tracks: {
          href: "https://api.spotify.com/v1/playlists/2JJKPRr2ODC4sYEVop2jTm/tracks",
          total: 0,
        },
        type: "playlist",
        uri: "spotify:playlist:2JJKPRr2ODC4sYEVop2jTm",
      },
      {
        collaborative: false,
        description: "123",
        external_urls: {
          spotify: "https://open.spotify.com/playlist/4bDciRNTuJEYi3ZGO9X9W8",
        },
        href: "https://api.spotify.com/v1/playlists/4bDciRNTuJEYi3ZGO9X9W8",
        id: "4bDciRNTuJEYi3ZGO9X9W8",
        images: null,
        name: "Khanhdua2@",
        owner: {
          display_name: "Khánh Lê Mai Quốc",
          external_urls: {
            spotify: "https://open.spotify.com/user/31gcx7qzn7bcsyh6vn72rul4afki",
          },
          href: "https://api.spotify.com/v1/users/31gcx7qzn7bcsyh6vn72rul4afki",
          id: "31gcx7qzn7bcsyh6vn72rul4afki",
          type: "user",
          uri: "spotify:user:31gcx7qzn7bcsyh6vn72rul4afki",
        },
        primary_color: null,
        public: true,
        snapshot_id: "AAAAAYRKaScW6Ez7peX8cvfQcpCqOXvL",
        tracks: {
          href: "https://api.spotify.com/v1/playlists/4bDciRNTuJEYi3ZGO9X9W8/tracks",
          total: 0,
        },
        type: "playlist",
        uri: "spotify:playlist:4bDciRNTuJEYi3ZGO9X9W8",
      },
      {
        collaborative: false,
        description: "",
        external_urls: {
          spotify: "https://open.spotify.com/playlist/4UUbIET0XdPhp7xErl3nLI",
        },
        href: "https://api.spotify.com/v1/playlists/4UUbIET0XdPhp7xErl3nLI",
        id: "4UUbIET0XdPhp7xErl3nLI",
        images: null,
        name: "123",
        owner: {
          display_name: "Khánh Lê Mai Quốc",
          external_urls: {
            spotify: "https://open.spotify.com/user/31gcx7qzn7bcsyh6vn72rul4afki",
          },
          href: "https://api.spotify.com/v1/users/31gcx7qzn7bcsyh6vn72rul4afki",
          id: "31gcx7qzn7bcsyh6vn72rul4afki",
          type: "user",
          uri: "spotify:user:31gcx7qzn7bcsyh6vn72rul4afki",
        },
        primary_color: null,
        public: true,
        snapshot_id: "AAAAAdxcnq4+CrkF4OflZUB5uwW3gpp9",
        tracks: {
          href: "https://api.spotify.com/v1/playlists/4UUbIET0XdPhp7xErl3nLI/tracks",
          total: 0,
        },
        type: "playlist",
        uri: "spotify:playlist:4UUbIET0XdPhp7xErl3nLI",
      },
      {
        collaborative: false,
        description: "123123",
        external_urls: {
          spotify: "https://open.spotify.com/playlist/1I3AFw9qFM4ORKUySGYzZa",
        },
        href: "https://api.spotify.com/v1/playlists/1I3AFw9qFM4ORKUySGYzZa",
        id: "1I3AFw9qFM4ORKUySGYzZa",
        images: null,
        name: "Tui la ai",
        owner: {
          display_name: "Khánh Lê Mai Quốc",
          external_urls: {
            spotify: "https://open.spotify.com/user/31gcx7qzn7bcsyh6vn72rul4afki",
          },
          href: "https://api.spotify.com/v1/users/31gcx7qzn7bcsyh6vn72rul4afki",
          id: "31gcx7qzn7bcsyh6vn72rul4afki",
          type: "user",
          uri: "spotify:user:31gcx7qzn7bcsyh6vn72rul4afki",
        },
        primary_color: null,
        public: true,
        snapshot_id: "AAAAAWkxDJ6iYzutCdb1W7Gtx2iDN5ND",
        tracks: {
          href: "https://api.spotify.com/v1/playlists/1I3AFw9qFM4ORKUySGYzZa/tracks",
          total: 0,
        },
        type: "playlist",
        uri: "spotify:playlist:1I3AFw9qFM4ORKUySGYzZa",
      },
      {
        collaborative: false,
        description: "123",
        external_urls: {
          spotify: "https://open.spotify.com/playlist/1SKYB4cQtIaiBMZQjuudHZ",
        },
        href: "https://api.spotify.com/v1/playlists/1SKYB4cQtIaiBMZQjuudHZ",
        id: "1SKYB4cQtIaiBMZQjuudHZ",
        images: null,
        name: "khanh",
        owner: {
          display_name: "Khánh Lê Mai Quốc",
          external_urls: {
            spotify: "https://open.spotify.com/user/31gcx7qzn7bcsyh6vn72rul4afki",
          },
          href: "https://api.spotify.com/v1/users/31gcx7qzn7bcsyh6vn72rul4afki",
          id: "31gcx7qzn7bcsyh6vn72rul4afki",
          type: "user",
          uri: "spotify:user:31gcx7qzn7bcsyh6vn72rul4afki",
        },
        primary_color: null,
        public: true,
        snapshot_id: "AAAAAf0cvFzF+Yy+8ZyOlZlt//+4wDrs",
        tracks: {
          href: "https://api.spotify.com/v1/playlists/1SKYB4cQtIaiBMZQjuudHZ/tracks",
          total: 0,
        },
        type: "playlist",
        uri: "spotify:playlist:1SKYB4cQtIaiBMZQjuudHZ",
      },
      {
        collaborative: false,
        description: "123",
        external_urls: {
          spotify: "https://open.spotify.com/playlist/76lxMG4PCB4xVNA6bR2c4M",
        },
        href: "https://api.spotify.com/v1/playlists/76lxMG4PCB4xVNA6bR2c4M",
        id: "76lxMG4PCB4xVNA6bR2c4M",
        images: null,
        name: "123",
        owner: {
          display_name: "Khánh Lê Mai Quốc",
          external_urls: {
            spotify: "https://open.spotify.com/user/31gcx7qzn7bcsyh6vn72rul4afki",
          },
          href: "https://api.spotify.com/v1/users/31gcx7qzn7bcsyh6vn72rul4afki",
          id: "31gcx7qzn7bcsyh6vn72rul4afki",
          type: "user",
          uri: "spotify:user:31gcx7qzn7bcsyh6vn72rul4afki",
        },
        primary_color: null,
        public: true,
        snapshot_id: "AAAAAZc2Jn3per7MRRB37j0V88cYa8r6",
        tracks: {
          href: "https://api.spotify.com/v1/playlists/76lxMG4PCB4xVNA6bR2c4M/tracks",
          total: 0,
        },
        type: "playlist",
        uri: "spotify:playlist:76lxMG4PCB4xVNA6bR2c4M",
      },
      {
        collaborative: false,
        description: "123",
        external_urls: {
          spotify: "https://open.spotify.com/playlist/2BE0qOEtRQAk8ix5H4bLIZ",
        },
        href: "https://api.spotify.com/v1/playlists/2BE0qOEtRQAk8ix5H4bLIZ",
        id: "2BE0qOEtRQAk8ix5H4bLIZ",
        images: null,
        name: "123",
        owner: {
          display_name: "Khánh Lê Mai Quốc",
          external_urls: {
            spotify: "https://open.spotify.com/user/31gcx7qzn7bcsyh6vn72rul4afki",
          },
          href: "https://api.spotify.com/v1/users/31gcx7qzn7bcsyh6vn72rul4afki",
          id: "31gcx7qzn7bcsyh6vn72rul4afki",
          type: "user",
          uri: "spotify:user:31gcx7qzn7bcsyh6vn72rul4afki",
        },
        primary_color: null,
        public: true,
        snapshot_id: "AAAAAUcGIvvYCuBev2zsNmZh7ByYSiD5",
        tracks: {
          href: "https://api.spotify.com/v1/playlists/2BE0qOEtRQAk8ix5H4bLIZ/tracks",
          total: 0,
        },
        type: "playlist",
        uri: "spotify:playlist:2BE0qOEtRQAk8ix5H4bLIZ",
      },
      {
        collaborative: false,
        description: "123123",
        external_urls: {
          spotify: "https://open.spotify.com/playlist/55IuRkP0rOagBizPwLR4hR",
        },
        href: "https://api.spotify.com/v1/playlists/55IuRkP0rOagBizPwLR4hR",
        id: "55IuRkP0rOagBizPwLR4hR",
        images: null,
        name: "12312312312312313123123",
        owner: {
          display_name: "Khánh Lê Mai Quốc",
          external_urls: {
            spotify: "https://open.spotify.com/user/31gcx7qzn7bcsyh6vn72rul4afki",
          },
          href: "https://api.spotify.com/v1/users/31gcx7qzn7bcsyh6vn72rul4afki",
          id: "31gcx7qzn7bcsyh6vn72rul4afki",
          type: "user",
          uri: "spotify:user:31gcx7qzn7bcsyh6vn72rul4afki",
        },
        primary_color: null,
        public: true,
        snapshot_id: "AAAAATV6gRqwgvKR7J045ZRumKLzlTXm",
        tracks: {
          href: "https://api.spotify.com/v1/playlists/55IuRkP0rOagBizPwLR4hR/tracks",
          total: 0,
        },
        type: "playlist",
        uri: "spotify:playlist:55IuRkP0rOagBizPwLR4hR",
      },
      {
        collaborative: false,
        description: "123123",
        external_urls: {
          spotify: "https://open.spotify.com/playlist/7JqTkx6AFMXT7dlA5Ri14S",
        },
        href: "https://api.spotify.com/v1/playlists/7JqTkx6AFMXT7dlA5Ri14S",
        id: "7JqTkx6AFMXT7dlA5Ri14S",
        images: null,
        name: "123123123123123",
        owner: {
          display_name: "Khánh Lê Mai Quốc",
          external_urls: {
            spotify: "https://open.spotify.com/user/31gcx7qzn7bcsyh6vn72rul4afki",
          },
          href: "https://api.spotify.com/v1/users/31gcx7qzn7bcsyh6vn72rul4afki",
          id: "31gcx7qzn7bcsyh6vn72rul4afki",
          type: "user",
          uri: "spotify:user:31gcx7qzn7bcsyh6vn72rul4afki",
        },
        primary_color: null,
        public: true,
        snapshot_id: "AAAAAad9ObRGnju2o5Ztlo59DjAZULyb",
        tracks: {
          href: "https://api.spotify.com/v1/playlists/7JqTkx6AFMXT7dlA5Ri14S/tracks",
          total: 0,
        },
        type: "playlist",
        uri: "spotify:playlist:7JqTkx6AFMXT7dlA5Ri14S",
      },
      {
        collaborative: false,
        description: "123",
        external_urls: {
          spotify: "https://open.spotify.com/playlist/6DEg0SZLGxxWv7mmJibaYB",
        },
        href: "https://api.spotify.com/v1/playlists/6DEg0SZLGxxWv7mmJibaYB",
        id: "6DEg0SZLGxxWv7mmJibaYB",
        images: null,
        name: "123",
        owner: {
          display_name: "Khánh Lê Mai Quốc",
          external_urls: {
            spotify: "https://open.spotify.com/user/31gcx7qzn7bcsyh6vn72rul4afki",
          },
          href: "https://api.spotify.com/v1/users/31gcx7qzn7bcsyh6vn72rul4afki",
          id: "31gcx7qzn7bcsyh6vn72rul4afki",
          type: "user",
          uri: "spotify:user:31gcx7qzn7bcsyh6vn72rul4afki",
        },
        primary_color: null,
        public: true,
        snapshot_id: "AAAAAeaWoBb59uiFI7tm+rui/U4U6P9H",
        tracks: {
          href: "https://api.spotify.com/v1/playlists/6DEg0SZLGxxWv7mmJibaYB/tracks",
          total: 0,
        },
        type: "playlist",
        uri: "spotify:playlist:6DEg0SZLGxxWv7mmJibaYB",
      },
      {
        collaborative: false,
        description: "123",
        external_urls: {
          spotify: "https://open.spotify.com/playlist/7ofXUXns0bSqSCiZKZiLtA",
        },
        href: "https://api.spotify.com/v1/playlists/7ofXUXns0bSqSCiZKZiLtA",
        id: "7ofXUXns0bSqSCiZKZiLtA",
        images: null,
        name: "123",
        owner: {
          display_name: "Khánh Lê Mai Quốc",
          external_urls: {
            spotify: "https://open.spotify.com/user/31gcx7qzn7bcsyh6vn72rul4afki",
          },
          href: "https://api.spotify.com/v1/users/31gcx7qzn7bcsyh6vn72rul4afki",
          id: "31gcx7qzn7bcsyh6vn72rul4afki",
          type: "user",
          uri: "spotify:user:31gcx7qzn7bcsyh6vn72rul4afki",
        },
        primary_color: null,
        public: true,
        snapshot_id: "AAAAAXa7CuyZ+XHVQdQjtisUK7be5KG0",
        tracks: {
          href: "https://api.spotify.com/v1/playlists/7ofXUXns0bSqSCiZKZiLtA/tracks",
          total: 0,
        },
        type: "playlist",
        uri: "spotify:playlist:7ofXUXns0bSqSCiZKZiLtA",
      },
      {
        collaborative: false,
        description: "",
        external_urls: {
          spotify: "https://open.spotify.com/playlist/67o8Dd9xAniaH35qAU2nLr",
        },
        href: "https://api.spotify.com/v1/playlists/67o8Dd9xAniaH35qAU2nLr",
        id: "67o8Dd9xAniaH35qAU2nLr",
        images: null,
        name: "123",
        owner: {
          display_name: "Khánh Lê Mai Quốc",
          external_urls: {
            spotify: "https://open.spotify.com/user/31gcx7qzn7bcsyh6vn72rul4afki",
          },
          href: "https://api.spotify.com/v1/users/31gcx7qzn7bcsyh6vn72rul4afki",
          id: "31gcx7qzn7bcsyh6vn72rul4afki",
          type: "user",
          uri: "spotify:user:31gcx7qzn7bcsyh6vn72rul4afki",
        },
        primary_color: null,
        public: true,
        snapshot_id: "AAAAAfN5ZzUIDLPEx7DoKi7i0S8FNEt9",
        tracks: {
          href: "https://api.spotify.com/v1/playlists/67o8Dd9xAniaH35qAU2nLr/tracks",
          total: 0,
        },
        type: "playlist",
        uri: "spotify:playlist:67o8Dd9xAniaH35qAU2nLr",
      },
      {
        collaborative: false,
        description: "1",
        external_urls: {
          spotify: "https://open.spotify.com/playlist/73H8gv63us39RiOnBS27bC",
        },
        href: "https://api.spotify.com/v1/playlists/73H8gv63us39RiOnBS27bC",
        id: "73H8gv63us39RiOnBS27bC",
        images: null,
        name: "1",
        owner: {
          display_name: "Khánh Lê Mai Quốc",
          external_urls: {
            spotify: "https://open.spotify.com/user/31gcx7qzn7bcsyh6vn72rul4afki",
          },
          href: "https://api.spotify.com/v1/users/31gcx7qzn7bcsyh6vn72rul4afki",
          id: "31gcx7qzn7bcsyh6vn72rul4afki",
          type: "user",
          uri: "spotify:user:31gcx7qzn7bcsyh6vn72rul4afki",
        },
        primary_color: null,
        public: true,
        snapshot_id: "AAAAAVEONeDQ2Sm62s1W/d2HC5lOoVLA",
        tracks: {
          href: "https://api.spotify.com/v1/playlists/73H8gv63us39RiOnBS27bC/tracks",
          total: 0,
        },
        type: "playlist",
        uri: "spotify:playlist:73H8gv63us39RiOnBS27bC",
      },
      {
        collaborative: false,
        description: "123",
        external_urls: {
          spotify: "https://open.spotify.com/playlist/2LRbDCenyyeJxlQpScvwMN",
        },
        href: "https://api.spotify.com/v1/playlists/2LRbDCenyyeJxlQpScvwMN",
        id: "2LRbDCenyyeJxlQpScvwMN",
        images: null,
        name: "Lê Mai Quốc Khánh",
        owner: {
          display_name: "Khánh Lê Mai Quốc",
          external_urls: {
            spotify: "https://open.spotify.com/user/31gcx7qzn7bcsyh6vn72rul4afki",
          },
          href: "https://api.spotify.com/v1/users/31gcx7qzn7bcsyh6vn72rul4afki",
          id: "31gcx7qzn7bcsyh6vn72rul4afki",
          type: "user",
          uri: "spotify:user:31gcx7qzn7bcsyh6vn72rul4afki",
        },
        primary_color: null,
        public: true,
        snapshot_id: "AAAAARYlVOzId6NLVDDvf6Ikhaq+qpaK",
        tracks: {
          href: "https://api.spotify.com/v1/playlists/2LRbDCenyyeJxlQpScvwMN/tracks",
          total: 0,
        },
        type: "playlist",
        uri: "spotify:playlist:2LRbDCenyyeJxlQpScvwMN",
      },
      {
        collaborative: false,
        description: "",
        external_urls: {
          spotify: "https://open.spotify.com/playlist/0n1fSlCZJGSZ9moGyvOG0Z",
        },
        href: "https://api.spotify.com/v1/playlists/0n1fSlCZJGSZ9moGyvOG0Z",
        id: "0n1fSlCZJGSZ9moGyvOG0Z",
        images: null,
        name: "My Playlist #10",
        owner: {
          display_name: "Khánh Lê Mai Quốc",
          external_urls: {
            spotify: "https://open.spotify.com/user/31gcx7qzn7bcsyh6vn72rul4afki",
          },
          href: "https://api.spotify.com/v1/users/31gcx7qzn7bcsyh6vn72rul4afki",
          id: "31gcx7qzn7bcsyh6vn72rul4afki",
          type: "user",
          uri: "spotify:user:31gcx7qzn7bcsyh6vn72rul4afki",
        },
        primary_color: null,
        public: true,
        snapshot_id: "AAAAAeTw55IvRWwx4/oUsOHo80MsbxjH",
        tracks: {
          href: "https://api.spotify.com/v1/playlists/0n1fSlCZJGSZ9moGyvOG0Z/tracks",
          total: 0,
        },
        type: "playlist",
        uri: "spotify:playlist:0n1fSlCZJGSZ9moGyvOG0Z",
      },
      {
        collaborative: false,
        description: "123",
        external_urls: {
          spotify: "https://open.spotify.com/playlist/5y63s2m0oHGiHcv3VXikuE",
        },
        href: "https://api.spotify.com/v1/playlists/5y63s2m0oHGiHcv3VXikuE",
        id: "5y63s2m0oHGiHcv3VXikuE",
        images: null,
        name: "khanhdua2",
        owner: {
          display_name: "Khánh Lê Mai Quốc",
          external_urls: {
            spotify: "https://open.spotify.com/user/31gcx7qzn7bcsyh6vn72rul4afki",
          },
          href: "https://api.spotify.com/v1/users/31gcx7qzn7bcsyh6vn72rul4afki",
          id: "31gcx7qzn7bcsyh6vn72rul4afki",
          type: "user",
          uri: "spotify:user:31gcx7qzn7bcsyh6vn72rul4afki",
        },
        primary_color: null,
        public: true,
        snapshot_id: "AAAAAV5ubLK2boiFdehdKqpEfrMnsOp8",
        tracks: {
          href: "https://api.spotify.com/v1/playlists/5y63s2m0oHGiHcv3VXikuE/tracks",
          total: 0,
        },
        type: "playlist",
        uri: "spotify:playlist:5y63s2m0oHGiHcv3VXikuE",
      },
      {
        collaborative: false,
        description: "123",
        external_urls: {
          spotify: "https://open.spotify.com/playlist/63pXDj69oUPq4W4O80oclR",
        },
        href: "https://api.spotify.com/v1/playlists/63pXDj69oUPq4W4O80oclR",
        id: "63pXDj69oUPq4W4O80oclR",
        images: null,
        name: "hi",
        owner: {
          display_name: "Khánh Lê Mai Quốc",
          external_urls: {
            spotify: "https://open.spotify.com/user/31gcx7qzn7bcsyh6vn72rul4afki",
          },
          href: "https://api.spotify.com/v1/users/31gcx7qzn7bcsyh6vn72rul4afki",
          id: "31gcx7qzn7bcsyh6vn72rul4afki",
          type: "user",
          uri: "spotify:user:31gcx7qzn7bcsyh6vn72rul4afki",
        },
        primary_color: null,
        public: true,
        snapshot_id: "AAAAAWhKynUQ1WJV+IVd9zbqADCxj24z",
        tracks: {
          href: "https://api.spotify.com/v1/playlists/63pXDj69oUPq4W4O80oclR/tracks",
          total: 0,
        },
        type: "playlist",
        uri: "spotify:playlist:63pXDj69oUPq4W4O80oclR",
      },
      {
        collaborative: false,
        description: "123123123",
        external_urls: {
          spotify: "https://open.spotify.com/playlist/0xqcrbr0nYPrDHt3919PIb",
        },
        href: "https://api.spotify.com/v1/playlists/0xqcrbr0nYPrDHt3919PIb",
        id: "0xqcrbr0nYPrDHt3919PIb",
        images: null,
        name: "Le mai quoc khanh",
        owner: {
          display_name: "Khánh Lê Mai Quốc",
          external_urls: {
            spotify: "https://open.spotify.com/user/31gcx7qzn7bcsyh6vn72rul4afki",
          },
          href: "https://api.spotify.com/v1/users/31gcx7qzn7bcsyh6vn72rul4afki",
          id: "31gcx7qzn7bcsyh6vn72rul4afki",
          type: "user",
          uri: "spotify:user:31gcx7qzn7bcsyh6vn72rul4afki",
        },
        primary_color: null,
        public: true,
        snapshot_id: "AAAAAfQvXlGMp+5rrlH8LL/iZwTyKMF7",
        tracks: {
          href: "https://api.spotify.com/v1/playlists/0xqcrbr0nYPrDHt3919PIb/tracks",
          total: 0,
        },
        type: "playlist",
        uri: "spotify:playlist:0xqcrbr0nYPrDHt3919PIb",
      },
      {
        collaborative: false,
        description: "khanhdua2",
        external_urls: {
          spotify: "https://open.spotify.com/playlist/5ilaYIbORRazBnv0KyJGeQ",
        },
        href: "https://api.spotify.com/v1/playlists/5ilaYIbORRazBnv0KyJGeQ",
        id: "5ilaYIbORRazBnv0KyJGeQ",
        images: null,
        name: "khanhdua2",
        owner: {
          display_name: "Khánh Lê Mai Quốc",
          external_urls: {
            spotify: "https://open.spotify.com/user/31gcx7qzn7bcsyh6vn72rul4afki",
          },
          href: "https://api.spotify.com/v1/users/31gcx7qzn7bcsyh6vn72rul4afki",
          id: "31gcx7qzn7bcsyh6vn72rul4afki",
          type: "user",
          uri: "spotify:user:31gcx7qzn7bcsyh6vn72rul4afki",
        },
        primary_color: null,
        public: true,
        snapshot_id: "AAAAAc6JEkL+4UNt8smMk9xutfphIJG9",
        tracks: {
          href: "https://api.spotify.com/v1/playlists/5ilaYIbORRazBnv0KyJGeQ/tracks",
          total: 0,
        },
        type: "playlist",
        uri: "spotify:playlist:5ilaYIbORRazBnv0KyJGeQ",
      },
      {
        collaborative: false,
        description: "khanhdua2",
        external_urls: {
          spotify: "https://open.spotify.com/playlist/24jSiej4XpXSX7E8iqfv9C",
        },
        href: "https://api.spotify.com/v1/playlists/24jSiej4XpXSX7E8iqfv9C",
        id: "24jSiej4XpXSX7E8iqfv9C",
        images: null,
        name: "khanhdua2",
        owner: {
          display_name: "Khánh Lê Mai Quốc",
          external_urls: {
            spotify: "https://open.spotify.com/user/31gcx7qzn7bcsyh6vn72rul4afki",
          },
          href: "https://api.spotify.com/v1/users/31gcx7qzn7bcsyh6vn72rul4afki",
          id: "31gcx7qzn7bcsyh6vn72rul4afki",
          type: "user",
          uri: "spotify:user:31gcx7qzn7bcsyh6vn72rul4afki",
        },
        primary_color: null,
        public: true,
        snapshot_id: "AAAAAXq0w/SjsdM/BaGj4Vr95z0mszDX",
        tracks: {
          href: "https://api.spotify.com/v1/playlists/24jSiej4XpXSX7E8iqfv9C/tracks",
          total: 0,
        },
        type: "playlist",
        uri: "spotify:playlist:24jSiej4XpXSX7E8iqfv9C",
      },
      {
        collaborative: false,
        description: "123123123",
        external_urls: {
          spotify: "https://open.spotify.com/playlist/5VIo7EZg89Jizzf4NrBR6x",
        },
        href: "https://api.spotify.com/v1/playlists/5VIo7EZg89Jizzf4NrBR6x",
        id: "5VIo7EZg89Jizzf4NrBR6x",
        images: null,
        name: "123123",
        owner: {
          display_name: "Khánh Lê Mai Quốc",
          external_urls: {
            spotify: "https://open.spotify.com/user/31gcx7qzn7bcsyh6vn72rul4afki",
          },
          href: "https://api.spotify.com/v1/users/31gcx7qzn7bcsyh6vn72rul4afki",
          id: "31gcx7qzn7bcsyh6vn72rul4afki",
          type: "user",
          uri: "spotify:user:31gcx7qzn7bcsyh6vn72rul4afki",
        },
        primary_color: null,
        public: true,
        snapshot_id: "AAAAAUIS3b68gzUpDGIg3OKKCneS6zlI",
        tracks: {
          href: "https://api.spotify.com/v1/playlists/5VIo7EZg89Jizzf4NrBR6x/tracks",
          total: 0,
        },
        type: "playlist",
        uri: "spotify:playlist:5VIo7EZg89Jizzf4NrBR6x",
      },
      {
        collaborative: false,
        description: "",
        external_urls: {
          spotify: "https://open.spotify.com/playlist/0BRdj6rnqeJLsU4v5K9Hh0",
        },
        href: "https://api.spotify.com/v1/playlists/0BRdj6rnqeJLsU4v5K9Hh0",
        id: "0BRdj6rnqeJLsU4v5K9Hh0",
        images: null,
        name: "My Playlist #2",
        owner: {
          display_name: "Khánh Lê Mai Quốc",
          external_urls: {
            spotify: "https://open.spotify.com/user/31gcx7qzn7bcsyh6vn72rul4afki",
          },
          href: "https://api.spotify.com/v1/users/31gcx7qzn7bcsyh6vn72rul4afki",
          id: "31gcx7qzn7bcsyh6vn72rul4afki",
          type: "user",
          uri: "spotify:user:31gcx7qzn7bcsyh6vn72rul4afki",
        },
        primary_color: null,
        public: true,
        snapshot_id: "AAAAAcjKqFRuPAoE5zr7+rE2yK4eM8Ug",
        tracks: {
          href: "https://api.spotify.com/v1/playlists/0BRdj6rnqeJLsU4v5K9Hh0/tracks",
          total: 0,
        },
        type: "playlist",
        uri: "spotify:playlist:0BRdj6rnqeJLsU4v5K9Hh0",
      },
      {
        collaborative: false,
        description: "",
        external_urls: {
          spotify: "https://open.spotify.com/playlist/0YHfwtDc48gHLKnl85GfA3",
        },
        href: "https://api.spotify.com/v1/playlists/0YHfwtDc48gHLKnl85GfA3",
        id: "0YHfwtDc48gHLKnl85GfA3",
        images: null,
        name: "My Playlist #1",
        owner: {
          display_name: "Khánh Lê Mai Quốc",
          external_urls: {
            spotify: "https://open.spotify.com/user/31gcx7qzn7bcsyh6vn72rul4afki",
          },
          href: "https://api.spotify.com/v1/users/31gcx7qzn7bcsyh6vn72rul4afki",
          id: "31gcx7qzn7bcsyh6vn72rul4afki",
          type: "user",
          uri: "spotify:user:31gcx7qzn7bcsyh6vn72rul4afki",
        },
        primary_color: null,
        public: true,
        snapshot_id: "AAAAAS1+P60I8oj+DLuLBKx2eEKjla2m",
        tracks: {
          href: "https://api.spotify.com/v1/playlists/0YHfwtDc48gHLKnl85GfA3/tracks",
          total: 0,
        },
        type: "playlist",
        uri: "spotify:playlist:0YHfwtDc48gHLKnl85GfA3",
      },
    ],
  };
  playlists?.items?.forEach(async (item) => {
    console.log(item.owner.id);
    // await spotifyAPIDelete(`/playlists/${item.owner.id}/tracks`);
  });
  return (
    <div className="App">
      <Suspense fallback={<div>Loading...</div>}>
        <Routes>
          {publicRoutes.map((route, index) => {
            const Page = route.component;
            return (
              <Route
                key={index}
                path={route.path}
                element={
                  route.mainLayout ? (
                    <MainLayout>
                      <Page />
                    </MainLayout>
                  ) : (
                    <Page />
                  )
                }
              />
            );
          })}
        </Routes>
      </Suspense>
    </div>
  );
}

export default App;
